### ISSUE TITLE
tabularcv specs

### ISSUE THREAD

**Issue by VeronicaCraine** [Roald87/xelatex-cv-roald#5]
Hello,
Is it possible to have the entire table width match the margins set via \geometry?
I edited the original left and right margins to be 2cm each. The left of the table lines up well with the text margin, however, the table is much shorter than the right text margin.
Thank you.

**Comment by Roald87** [comment]
If you change `\setlength{\margin}{25mm}` directly in `cv-roald.cls` it should calculate the correct table widths.
