### ISSUE TITLE
Error with TeXLive2020 kvoptions-patch conflict.

### ISSUE THREAD

**Issue by laenan8466** [Roald87/xelatex-cv-roald#6]
Hey,
first thank you for the template. It is wonderful!

Sadly, with TexLive2020, it is not working anymore, as there is an issue with kvoptions-patch. I asked a related question on TeX stackexchange: https://tex.stackexchange.com/questions/572584/changes-from-texlive-2017-2020

I will try if I can find a solution, but not sure if I have the time.

Further resources on the issue:
[kvoption package announcement concerning this issue](https://ctan.org/ctan-ann/id/mailman.3737.1602335541.2548.ctan-ann@ctan.org)
[issue on github](https://github.com/ho-tex/kvoptions/issues/5)

**Comment by Roald87** [comment]
Hey @laenan8466,

Glad to hear that my 3 year old template is still enjoyed by people!

Thanks for the investigation into the source of the problem! I will try to find a solution, but I haven't used LaTeX in some time, so I'll have to get into it again :).

Roald.

**Comment by laenan8466** [comment]
Hey,
it's me again. Of course people are working with it: Oldies but goodies... ;-)

I started working on a resolution, and faced a 'decision' that I have to make. Stumbled over it, as I was creating a new class (similar to your cv) for my cover letter. And I need your opinion:
Would you favor to change the compiler to lualatex or stay with xelatex? Just because I read in the TeX manual:
[LuaTEXis the designated successor of pdfTEX](https://www.tug.org/texlive/doc/texlive-en/texlive-en.pdf)

I have no strong opinion here, ...

EDIT: I played around a bit with LuaLaTeX. Although it is designated to be the future, I would recommend to continue using XeLaTex. I wasn't even able to run:

```latex
% !TeX program = lualatex
\documentclass{standalone}

\begin{document}
	Inhalt...
\end{document}
```

They manage the fonts from the system fonts and there is some issue on my (Windows) machine.

**Comment by u-fischer** [comment]
> They manage the fonts from the system fonts and there is some issue on my (Windows) machine. 

I have windows too, and lualatex works for me (and my other people) without any problems. 

Beside this: nothing in the class is xelatex specific, it should work with lualatex too. But the class should remove the cellspace patch, cellspace has been adapted and contains the fix. And there is no need to load color if tikz is loaded.

**Comment by laenan8466** [comment]
Thanks for stepping in! :-)
Most probably, it's sth amiss on my machine, as LuaLaTeX is working fine on my other one. Sadly, I just hadn't had the patience to fix it that day.
I will look into the cellspace tomorrow. 
@Roald87 I had the feeling, that cellspace wasn't working for me properly, and I got quite narrow bottom lines. Did you expect the same thing?

**Comment by Roald87** [comment]
I just tried to compile the example cv with different tex live versions (2020, 2019 and 2016) on Overleaf. I had no issues with the `kvoptions-patch` package when I tried to compile it. It worked for both XeLaTeX as well as LuaTex.

I'll also install tex locally on my Ubuntu machine and see if I can compile it there.

I did notice that the spacing after the titles was different with texlive 2020 and that the cellspace was not working properly. Regarding the latter: As mentioned by @u-fischer this can be fixed by removing the code in the patch section:

```
% # REQUIRED PACKAGES
\RequirePackage{xpatch}

% Patch to prevent package color and cellspace to clash
% More info: https://tex.stackexchange.com/questions/384664/xcolor-package-disables-cellspace-package
\makeatletter
\xpatchcmd{\@endpbox}{\color@endgroup}{\expandafter\color@endgroup}{}{\ddt}
\makeatother
```

**Comment by laenan8466** [comment]
Hrm,
when your local install works fine as well, I guess it is my corrupted Windows installation... 
Ah, didn't understood the part with the patch completely.
Could one add a conditional check for the TeXLive (?) version in the xpatch section?

**Comment by Roald87** [comment]
> Could one add an conditional check for the TeXLive (?) version in the xpatch section?

Not sure. Let me check.

**Comment by Roald87** [comment]
> Could one add an conditional check for the TeXLive (?) version in the xpatch section?

Couldn't find an easy method to do this unfortunately.

**Comment by laenan8466** [comment]
Yep, I came to the same conclusion. For me I circumvent this by using an old latex version. If I update my version at any point and find a solution, I will let you know.

**Comment by j-jansen** [comment]
I had the same issue and I could solve it without changing to an old latex version but simply by replacing the package "kvoptions-patch" with "xkvltxp" in the .cls file. I did not have to change anything else.

**Comment by Roald87** [comment]
Thanks for letting us know!

**Comment by laenan8466** [comment]
Works for me as well as solution.  Had to adjust some margins/spacings, but nothing big.

I'm just a little bit hesitant as there is a reason why people switched from `xkvltxp` to `kvoptions-patch`. Also it seems to be quite old, isn't it? Not sure, if it is still under maintenance. 

But thank you! It worked for this problem and now I don't have to switch the computer to get a new date on my CV every time...

**Comment by Roald87** [comment]
[Docs](https://mirror.foobar.to/CTAN/macros/latex/contrib/xkeyval/xkeyval.pdf) were updated a few months ago, so looks like ` xkvltxp` is still maintained.

![afbeelding](https://user-images.githubusercontent.com/20192767/113431890-b4c79900-93dc-11eb-8ff9-24844c3d4b60.png)

**Comment by Freezeen** [comment]
Hey Guys, i just try to understand how this fix works, i use texworks and i really can not find this cls file.

I hope you can help me, this problem drives me crazy. :(

**Comment by Roald87** [comment]
@Freezeen what cls file do you mean?

**Comment by Freezeen** [comment]
> I had the same issue and I could solve it without changing to an old latex version but **simply by replacing the package "kvoptions-patch" with "xkvltxp" in the .cls file**. I did not have to change anything else.

I mean this one :) and thanks for the quick reply.

**Comment by Roald87** [comment]
> > I had the same issue and I could solve it without changing to an old latex version but **simply by replacing the package "kvoptions-patch" with "xkvltxp" in the .cls file**. I did not have to change anything else.
> 
> 
> 
> I mean this one :) and thanks for the quick reply.

No problem. Glad the template is still used! It is line 59 of cv-roald.cls

**Comment by Freezeen** [comment]
Many thanks it works great <3 You saved me :)

**Comment by laenan8466** [comment]
Close at this point as many solutions were given.

**Comment by Roald87** [comment]
Latest version 5.x.x works with TexLive 2023 on Overleaf. I do get an error that there are unused options, but all template options (`changecolor`, `titlecolor`, and `colorharmony`) work for me.
